#include "SpectraVulkanBackend.h"

#include "SpecVulkanCompiler.h"

SPEC_VK_BK_DIAGNOSTIC_PUSH
SPEC_VK_BK_DISABLE_WARNING(4100)
SPEC_VK_BK_DISABLE_WARNING(4189)
SPEC_VK_BK_DISABLE_WARNING(4324)

#define VMA_IMPLEMENTATION
#define VMA_VULKAN_VERSION 1003000
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 1
#include <vk_mem_alloc.h>

SPEC_VK_BK_DIAGNOSTIC_POP